[GLOBAL]
pants_version = "2.17.0"
backend_packages.add = [
  "pants.backend.build_files.fmt.black",  
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = ["/src", "/test"]

[python]
interpreter_constraints = ["==3.9.18"]
enable_resolves = true
resolves = { python-default = "lockfiles/default.lock"}

[python-bootstrap]
# https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
search_path = ["<PYENV>"]

[python-infer]
# 2.17 is transitioning to a new, faster parser for dependency inference:
use_rust_parser = true

[pytest]
args = ["-vv", "-s"]
