[GLOBAL]
pants_version = "2.18.0.dev1"
backend_packages.add = [
  "pants.backend.shell",
  "pants.backend.shell.lint.shellcheck",
  "pants.backend.shell.lint.shfmt",
  "pants.backend.build_files.fmt.black",  
  "pants.backend.python",
  "pants.backend.python.lint.autoflake",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  # TODO: Swap out for Ruff
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]
# local_store_dir = "/vol/biomedic3/rrr2417/.cache/lmdb_store"
# named_caches_dir = "/vol/biomedic3/rrr2417/.cache/named_caches"

[shfmt]
# See https://github.com/mvdan/sh/blob/master/cmd/shfmt/shfmt.1.scd#printer-flags.
args = ["-i 4", "-ci", "-sr"]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = ["/src", "/test"]

[python]
interpreter_constraints = ["==3.9.18"]
enable_resolves = true

[python.resolves]
python-default = "lockfiles/default.lock"
flake8 = "lockfiles/flake8.lock"
mypy = "lockfiles/mypy.lock"
pytest = "lockfiles/pytest.lock"

[python-bootstrap]
# https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
search_path = ["<PYENV>"]

[python-infer]
# 2.17 is transitioning to a new, faster parser for dependency inference:
use_rust_parser = true

[autoflake]
args = ["--ignore-init-module-imports"]

[flake8]
config = "build_support/flake8"
install_from_resolve = "flake8"

[mypy]
config = "build_support/mypy"
install_from_resolve = "mypy"

[pytest]
args = ["-vv", "-s"]
config = "build_support/pytest"
install_from_resolve = "pytest"
