python_sources()

pex_binary(
    name="x",
    entry_point="main.py",
    dependencies=[
        "3rdparty:reqs#wandb",
        "3rdparty:reqs#huggingface-hub",
        "3rdparty:reqs#regex",
        "3rdparty:reqs#safetensors",
        "3rdparty:reqs#tokenizers",
        "3rdparty:reqs#numpy",
        "3rdparty:reqs#sentencepiece",
        "3rdparty:reqs#sacremoses",
        "3rdparty:reqs#importlib-metadata",
    ],
)
